version: '3.7'
services:
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    restart: on-failure
    env_file:
      - ./init/database.env
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
  app:
    image: dev_db_image
    ports:
    - 8080:8080
    restart: on-failure
    env_file:
    - ./init/database.env
    volumes:
    - ./:/app
    depends_on:
      - postgresql
